name: ose-model-comparison
channels:
    - conda-forge
    - bioconda
dependencies:
    - python=3.6
    - numpy=1.15.4
    - pandas=0.22
    - matplotlib=3.0.2
    - seaborn=0.9.0
    - pandoc=2.5
    - pytest=4.0.2
    - flake8=3.6.0
    - snakemake-minimal=5.4
    - calliope=0.6.3
    - pip:
        - pytest-pythonpath # adds the root path "./" to PYTHONPATH
        - pandoc-tablenos
        - pandoc-fignos
        - pantable
