__default__:
    runtime: 10
    cores: 1
    memory: 16000
    output: "build/logs/{rule}.{wildcards}.log"
run_europe:
    runtime: 1440
    cores: 4
    memory: 28000
run_germany:
    cores: 4
    memory: 4000
test:
    runtime: 15
output:
    runtime: 60
ts_output:
    runtime: 60
