__default__:
    runtime: 10
    cores: 1
    memory: 16000
    output: "build/logs/{rule}.{wildcards}.log"
run:
    runtime: 1439
    cores: 4
    memory: 12000
test:
    runtime: 15
    cores: 1
    memory: 16000
