year: 2015
from_date: "2015-01-01"
to_date: "2015-12-31"
resolution: "2H"
scaling-factors:
    power: 0.001 # from MW to GW
    area: 0.001 # from km to 1000 km2
    monetary: 0.000001 # from EUR to Mio EUR
    co2: 1000 # from Mt to kt
scenarios:
    - baseline
    - low-cost
    - baseline-germany
    - low-cost-germany
